# tell docker permission is required
sudo: required
# tell travis to install docker
services:
  - docker

# initial commands
before_install:
  - docker build -t penabrea/docker-react -f Dockerfile.dev .

script:
  # we add -e CI=true to exit the terminal from wanting input
  - docker run -e CI=true penabrea/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker
  env: "Docker-env"
  # search elasticbeanstalk-** on s3 service
  bucket_name: "elasticbeanstalk-us-east-1-681726692303"
  bucket_path: "docker"
  on:
    # deploy only when master branch is update
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
